### ISSUE TITLE
`QueryString::extract()` returns inconsistent results compared to `parse_str()`

### ISSUE THREAD

**Issue by hafezdivandari** [thephpleague/uri-src#146] opened 2024-12-03 22:41 UTC
### Bug Report

| Information | Description |
|-------------|-------------|
| Package     | uri-interfaces |
| Version     | 7.4.1 |
| PHP version | 8.3 |

#### Summary

The `QueryString::extract()` method returns an unexpected result compared to PHP's `parse_str` method when handling a query that includes `[]`. However, the same query with `[0]` works as expected.

#### Standalone code, or other way to reproduce the problem

```php
use League\Uri\QueryString;
use function parse_str;

// The following test fails...
public function test_extract_query_string_with_empty_brackets()
{
    parse_str($query = 'key[][][foo][9]=bar', $result);

    $this->assertSame(['key' => [[['foo' => [9 => 'bar']]]]], $result);                      // passes
    $this->assertSame(['key' => [[['foo' => [9 => 'bar']]]]], QueryString::extract($query)); // fails
}

// The following test passes...
public function test_extract_query_string()
{
    parse_str($query = 'key[0][0][foo][9]=bar', $result);

    $this->assertSame(['key' => [[['foo' => [9 => 'bar']]]]], $result);                      // passes
    $this->assertSame(['key' => [[['foo' => [9 => 'bar']]]]], QueryString::extract($query)); // passes
}
```

#### Expected result

```php
$query = QueryString::extract('key[][][foo][9]=bar'); // expected: ['key' => [[['foo' => [9 => 'bar']]]]]
```

#### Actual result

```php
$query = QueryString::extract('key[][][foo][9]=bar'); // actual: ['key' => ['bar']]
```

**Comment by nyamsprod** [comment] 2024-12-04 15:24
The issue is resolved in the master branch and will be release with the next minor version 7.5.0

**Closed by nyamsprod** 2024-12-04 15:24 UTC
Labels: bug

**Comment by hafezdivandari** [comment] 2024-12-05 22:21
Thank you @nyamsprod, is there a due date for the 7.5 release?

**Comment by nyamsprod** [comment] 2024-12-07 23:27
@hafezdivandari should before the end of the year, hopefully next week depending on my day-job workload.

**Comment by nyamsprod** [comment] 2024-12-08 09:35
league/uri-interfaces `7.5.0` is released with the fix.
you should be able to use it as of league/uri `7.5.1`

**Comment by hafezdivandari** [comment] 2024-12-08 10:08
Thanks!
